name: Call s3 load

on: 
  workflow_dispatch:


env:
  DEV_TRIGGER_PREFIX: "experiment"
  PROD_TRIGGER_PREFIX: "release"

jobs:

  EnvDevSetup:

    name: Setup Dynamic DEV Environment Variables
    if:  startsWith(github.event.release.tag_name, ${{ env.DEV_TRIGGER_PREFIX }})
    runs-on: ubuntu-latest
    environment: DEV
    outputs:
      bucket-name: ${{ vars.BUCKET_NAME }}
      aws-region: ${{ vars.AWS_REGION }}

    steps:
      - run: echo "Exposing DEV env vars"
  
  EnvProdSetup:

    name: Setup Dynamic PROD Environment Variables
    if:  startsWith(github.event.release.tag_name,  ${{ env.PROD_TRIGGER_PREFIX }})
    runs-on: ubuntu-latest
    environment: PROD
    outputs:
      bucket-name: ${{ vars.BUCKET_NAME }}
      aws-region: ${{ vars.AWS_REGION }}

    steps:
      - run: echo "Exposing PROD env vars"


  call-workflow:

    permissions:
      id-token: write
      contents: read
    needs: [EnvDevSetup , EnvProdSetup]
    uses: hcastrofactored/github-actions-testing/.github/workflows/rw-deploy-multibranch.yml@main
    with:
      aws_region: us-east-1
      s3_path: ${{ vars.BUCKET_NAME }}
    secrets:
          aws_role_to_assume: ${{ secrets.ROLE_TO_ASSUME }}